### ISSUE TITLE
能支持idea么

### ISSUE THREAD

**Issue by Harlber** [Jamling/SmartQQ4Eclipse#1]
希望能支持`Intellij Idea`

**Comment by Jamling** [comment]
Intellij Idea暂时是不支持的。不过，我的最终目标就是在Intellij Idea上使用。因为我eclipse用得少。Intellij Idea用得多。

**Comment by Jamling** [comment]
The Intellij IDEA plugin has been release to https://plugins.jetbrains.com/plugin/9816-smartqq

Code: https://github.com/Jamling/SmartQQ4IntelliJ
