### ISSUE TITLE
'Show Console View' has encountered a problem.

### ISSUE THREAD

**Issue by goodwlj** [Jamling/SmartQQ4Eclipse#18]
Platform:
● MyEclipse Product(13.0.0.me201505171044):starting
Host plugin:
● SmartQQ(2.1.2):active

安装方式：Eclipse Marketplace（安装非常顺利）
登陆QQ顺利！
拉取信息顺利！
但是：打开聊天窗口出错：错误窗口如标题，错误详情如下：
An internal error has occurred.
org/eclipse/ui/console/IScrollLockStateProvider

**Comment by Jamling** [comment]
敬请期待下一版本：2.2.0 预计本周发布。

**Comment by Jamling** [comment]
fix in 3.0.0
