### ISSUE TITLE
关于安装和默认背景颜色的一点小问题

### ISSUE THREAD

**Issue by ViCrack** [Jamling/SmartQQ4Eclipse#19]
Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600
● SmartQQ(3.1.0.201803020925):active

在线安装的时候出现下图的问题，缺少依赖。
![222](https://user-images.githubusercontent.com/18179821/36898166-9d0d9248-1e54-11e8-9821-1398e6138411.png)
只能去找了eclipse-explorer先安装上去了，然后在安装SmartQQ4Eclipse就行了 ，不知道是不是我个人原因，记得旧版不用这样做。

eclipse改成暗色主题，编辑器等区域都是正常的黑色背景，但是SmartQQ4Eclipse的聊天窗体是白底的，  框字体也是浅色的，这样整体看起来就突兀了点吧。
![1](https://user-images.githubusercontent.com/18179821/36898259-0cf5a32a-1e55-11e8-8055-6ef9dde604ca.png)
![2](https://user-images.githubusercontent.com/18179821/36898310-40464342-1e55-11e8-96eb-b51cb1331b1b.png)
![11](https://user-images.githubusercontent.com/18179821/36898497-0a8e1652-1e56-11e8-8ad6-b9033189bd88.png)

不知道这颜色有地方能设置么？

**Comment by Jamling** [comment]
非常有建设性的意见~
1，3.x之后的版本需要依赖eclipse-explorer插件，原则上会自动安装依赖的插件，但我不清楚为何你的没有。估计是跟更新站点的配置有关。
2，聊天面板的颜色，是否可以截一个整图，比如整个SmartQQ面板的截图。颜色目前没有地方设置，敬请期待后续版本的更新。

**Comment by ViCrack** [comment]
这是包含SmartQQ面板的截图

![2222](https://user-images.githubusercontent.com/18179821/36953655-5e02da18-2057-11e8-8485-a03cc0fb46b3.png)

**Comment by Jamling** [comment]
已在3.1.1中优化。
