### ISSUE TITLE
Eclipse Jee Oxygen   乱码

### ISSUE THREAD

**Issue by ArvinLovegood** [Jamling/SmartQQ4Eclipse#4]
安装后 打开perferences > smartQQ 点击里面菜单都是乱码。不知道和工作空间设置的是UTF-8有没有关系

**Comment by Jamling** [comment]
属于eclipse插件打包时使用了默认的系统编码gbk导致。下个版本修复。

**Comment by Jamling** [comment]
在1.0.6中已修复
