### ISSUE TITLE
点击联系人列表不能打开聊天窗口

### ISSUE THREAD

**Issue by zhanglelife** [Jamling/SmartQQ4Eclipse#9]
弹窗提示以下:
An internal error has occurred.
org/eclipse/ui/console/IScrollLockStateProvider

**Comment by zhanglelife** [comment]
Eclipse IDE for Java Developers

Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600


smart qq
Platform:
● EPP Java Package(4.4.2.20150219-0708):resolved
Host plugin:
● SmartQQ(1.0.9):active

**Comment by Jamling** [comment]
估计是连接断开了，先关闭再重新登录试试

**Comment by runzhenghengbin** [comment]
点击联系人发消息。关闭重新连接也不想行
An internal error has occurred.
org/eclipse/ui/console/IScrollLockStateProvider

**Comment by Jamling** [comment]
目前发现Eclipse Luna Service Release 2 (4.4.2) 版本会出现此问题，因重写console过于复杂，所以暂时不修复此bug，请更换eclipse版本吧

**Comment by Jamling** [comment]
fix in 3.0.0
